- name: ScaleIO deployment
  hosts: all-sio-servers
  tasks:
    - name: Copy ScaleIO rpm files
      copy:
        src: /root/ScaleIO2.0.1.3Install/{{ item }}
        dest: /tmp/ 
      with_items:
        - 'EMC-ScaleIO-lia-2.0-13000.211.el7.x86_64.rpm'
        - 'EMC-ScaleIO-mdm-2.0-13000.211.el7.x86_64.rpm'
        - 'EMC-ScaleIO-sds-2.0-13000.211.el7.x86_64.rpm'

    - name: Install ScaleIO rpm files
      environment:
        TOKEN: 'P@ssw0rd'
      yum: 
        name: "{{ item }}"
        state: installed
      with_items:
        - '/tmp/EMC-ScaleIO-sds-2.0-13000.211.el7.x86_64.rpm'
        - '/tmp/EMC-ScaleIO-lia-2.0-13000.211.el7.x86_64.rpm'

- name: ScaleIO install mdm primary master
  hosts: scaleio-install-mdm12
  environment:
    MDM_ROLE_IS_MANAGER: 1
  tasks:
    - name: ScaleIO install mdm primary master
      yum: 
        name: "{{ item }}"
        state: installed
      with_items:
        - '/tmp/EMC-ScaleIO-mdm-2.0-13000.211.el7.x86_64.rpm'


- name: ScaleIO install mdm tie breaker
  hosts: scaleio-install-TB
  environment:
    MDM_ROLE_IS_MANAGER: 0 
  tasks:
    - name: ScaleIO install mdm tie breaker
      yum: 
        name: /tmp/EMC-ScaleIO-mdm-2.0-13000.211.el7.x86_64.rpm 

- name: ScaleIO cluster configuration
  hosts: Praimary-MDM
  environment:
    SDS1DATAIPS: '10.10.10.101,10.10.20.101' 
    SDS2DATAIPS: '10.10.10.102,10.10.20.102'  
    SDS3DATAIPS: '10.10.10.103,10.10.20.103'  
    SDS4DATAIPS: '10.10.10.104,10.10.20.104'
    SDS1MGMTIP: '172.31.240.34'
    SDS2MGMTIP: '172.31.240.59'
  tasks:
    - name: ScaleIO cluster configuration
      shell: | 
        scli --create_mdm_cluster --master_mdm_ip "$SDS1DATAIPS" --master_mdm_management_ip "$SDS1MGMTIP" --master_mdm_name mdm1 --accept_license --use_nonsecure_communication
        sleep 4 
        scli --login --username admin --password admin --approve_certificate
        scli --set_password --old_password admin --new_password P@ssw0rd 
        scli --login --username admin --password P@ssw0rd --approve_certificate
        scli --add_standby_mdm --new_mdm_ip "$SDS2DATAIPS" --mdm_role manager --new_mdm_management_ip "$SDS2MGMTIP" --new_mdm_name mdm2
        sleep 1 
        scli --add_standby_mdm --new_mdm_ip "$SDS3DATAIPS" --mdm_role tb --new_mdm_name tb 
        scli --switch_cluster_mode --cluster_mode 3_node --add_slave_mdm_name mdm2 --add_tb_name tb 
        
        sleep 2
         
        scli --add_protection_domain --protection_domain_name PD1
        scli --add_storage_pool --protection_domain_name PD1 --storage_pool_name POOL1

        scli --set_performance_parameters  --all_sds --all_sdc --apply_to_mdm --profile high_performance
        scli --rename_system --new_name SIOSYSTEM
        sleep 2

        scli --login --username admin --password P@ssw0rd --approve_certificate
        scli --add_sds --sds_ip "$SDS1DATAIPS" --device_path /dev/sdb --protection_domain_name PD1 --storage_pool_name POOL1 --sds_name sds1
        scli --add_sds --sds_ip "$SDS2DATAIPS" --device_path /dev/sdb --protection_domain_name PD1 --storage_pool_name POOL1 --sds_name sds2
        scli --add_sds --sds_ip "$SDS3DATAIPS" --device_path /dev/sdb --protection_domain_name PD1 --storage_pool_name POOL1 --sds_name sds3
        scli --add_sds --sds_ip "$SDS4DATAIPS" --device_path /dev/sdb --protection_domain_name PD1 --storage_pool_name POOL1 --sds_name sds4
